export type CnaeSugerido = { codigo: string; descricao: string }

export const CNAES_SUGERIDOS: CnaeSugerido[] = [
  { codigo: "4120-4/00", descricao: "Construção de edifícios" },
  { codigo: "4211-1/01", descricao: "Construção de rodovias e ferrovias" },
  { codigo: "4212-0/00", descricao: "Construção de obras de arte especiais" },
  { codigo: "4213-8/00", descricao: "Obras de urbanização — ruas, praças e calçadas" },
  { codigo: "4221-9/01", descricao: "Construção de barragens e represas" },
  { codigo: "4222-7/01", descricao: "Construção de redes de abastecimento de água" },
  { codigo: "4223-5/00", descricao: "Construção de redes de esgotos" },
  { codigo: "4291-0/00", descricao: "Obras portuárias, marítimas e fluviais" },
  { codigo: "4292-8/01", descricao: "Montagem de estruturas metálicas" },
  { codigo: "4299-5/01", descricao: "Construção de instalações esportivas e recreativas" },
  { codigo: "4311-8/01", descricao: "Demolição de edifícios e outras estruturas" },
  { codigo: "4321-5/00", descricao: "Instalação e manutenção elétrica" },
  { codigo: "4322-3/01", descricao: "Instalações hidráulicas, sanitárias e de gás" },
  { codigo: "4330-4/04", descricao: "Serviços de pintura de edifícios" },
  { codigo: "4399-1/03", descricao: "Obras de alvenaria" },
  { codigo: "4520-0/01", descricao: "Serviços de manutenção e reparação de automóveis" },
  { codigo: "4711-3/02", descricao: "Comércio varejista de mercadorias em geral — supermercados" },
  { codigo: "4731-8/00", descricao: "Comércio varejista de combustíveis" },
  { codigo: "4741-5/00", descricao: "Comércio varejista de tintas e materiais de construção" },
  { codigo: "4744-0/01", descricao: "Comércio varejista de ferragens e ferramentas" },
  { codigo: "4751-2/01", descricao: "Comércio varejista de equipamentos de informática" },
  { codigo: "4752-1/00", descricao: "Comércio varejista de material elétrico" },
  { codigo: "4753-9/00", descricao: "Comércio varejista de artigos de iluminação" },
  { codigo: "4761-0/01", descricao: "Comércio varejista de livros" },
  { codigo: "4771-7/01", descricao: "Comércio varejista de produtos farmacêuticos" },
  { codigo: "4911-6/00", descricao: "Transporte ferroviário de carga" },
  { codigo: "4921-3/01", descricao: "Transporte rodoviário coletivo de passageiros" },
  { codigo: "4930-2/01", descricao: "Transporte rodoviário de carga — exceto perigosa" },
  { codigo: "5020-1/00", descricao: "Transporte aquaviário de carga" },
  { codigo: "5111-1/00", descricao: "Transporte aéreo de passageiros regular" },
  { codigo: "5229-0/01", descricao: "Estacionamentos de veículos" },
  { codigo: "5611-2/01", descricao: "Restaurantes e similares" },
  { codigo: "5620-1/02", descricao: "Serviços de alimentação para eventos e recepções — buffet" },
  { codigo: "6110-8/01", descricao: "Serviços de telefonia fixa" },
  { codigo: "6120-5/01", descricao: "Telefonia móvel celular" },
  { codigo: "6190-6/99", descricao: "Serviços de comunicação" },
  { codigo: "6201-5/00", descricao: "Desenvolvimento de programas de computador sob encomenda" },
  { codigo: "6202-3/00", descricao: "Desenvolvimento e licenciamento de programas de computador" },
  { codigo: "6204-0/00", descricao: "Consultoria em tecnologia da informação" },
  { codigo: "6209-1/00", descricao: "Suporte técnico em tecnologia da informação" },
  { codigo: "6311-9/00", descricao: "Tratamento de dados, provedores de serviços de aplicação" },
  { codigo: "6319-4/00", descricao: "Portais, provedores de conteúdo e outros" },
  { codigo: "6910-6/00", descricao: "Atividades jurídicas" },
  { codigo: "6920-6/01", descricao: "Atividades de contabilidade" },
  { codigo: "7020-4/00", descricao: "Atividades de consultoria em gestão empresarial" },
  { codigo: "7111-1/00", descricao: "Serviços de arquitetura" },
  { codigo: "7112-0/00", descricao: "Serviços de engenharia" },
  { codigo: "7119-7/01", descricao: "Serviços de cartografia, topografia e geodésia" },
  { codigo: "7120-1/00", descricao: "Testes e análises técnicas" },
  { codigo: "7210-0/00", descricao: "Pesquisa e desenvolvimento em ciências físicas e naturais" },
  { codigo: "7311-4/00", descricao: "Agências de publicidade" },
  { codigo: "7319-0/99", descricao: "Outras atividades de publicidade" },
  { codigo: "7410-2/02", descricao: "Design de interiores" },
  { codigo: "7490-1/04", descricao: "Atividades de intermediação e agenciamento de serviços" },
  { codigo: "7500-1/00", descricao: "Atividades veterinárias" },
  { codigo: "7711-0/00", descricao: "Locação de automóveis sem condutor" },
  { codigo: "7719-5/99", descricao: "Locação de outros meios de transporte" },
  { codigo: "7721-7/00", descricao: "Aluguel de equipamentos recreativos e esportivos" },
  { codigo: "7732-2/02", descricao: "Aluguel de andaimes e equipamentos de construção" },
  { codigo: "7810-8/00", descricao: "Seleção e agenciamento de mão de obra" },
  { codigo: "7820-5/00", descricao: "Locação de mão de obra temporária" },
  { codigo: "7830-2/00", descricao: "Fornecimento e gestão de recursos humanos" },
  { codigo: "7911-2/00", descricao: "Agências de viagens" },
  { codigo: "8011-1/01", descricao: "Atividades de vigilância e segurança privada" },
  { codigo: "8020-0/01", descricao: "Atividades de monitoramento de alarmes" },
  { codigo: "8111-7/00", descricao: "Serviços combinados para apoio a edifícios" },
  { codigo: "8112-5/00", descricao: "Condomínios prediais" },
  { codigo: "8121-4/00", descricao: "Limpeza em prédios e em domicílios" },
  { codigo: "8122-2/00", descricao: "Imunização e controle de pragas urbanas" },
  { codigo: "8129-0/00", descricao: "Atividades de limpeza não especificadas" },
  { codigo: "8130-3/00", descricao: "Atividades paisagísticas" },
  { codigo: "8219-9/01", descricao: "Fotocópias" },
  { codigo: "8299-7/07", descricao: "Salas de acesso à internet" },
  { codigo: "8411-6/00", descricao: "Administração pública em geral" },
  { codigo: "8512-1/00", descricao: "Educação infantil — creches" },
  { codigo: "8513-9/00", descricao: "Educação infantil — pré-escola" },
  { codigo: "8520-1/00", descricao: "Ensino fundamental" },
  { codigo: "8531-7/00", descricao: "Educação superior — graduação" },
  { codigo: "8550-3/01", descricao: "Administração de caixas escolares" },
  { codigo: "8591-1/00", descricao: "Ensino de esportes" },
  { codigo: "8599-6/04", descricao: "Treinamento em desenvolvimento profissional e gerencial" },
  { codigo: "8610-1/01", descricao: "Atividades de atendimento hospitalar" },
  { codigo: "8621-6/02", descricao: "Serviços móveis de atendimento a urgências" },
  { codigo: "8630-5/01", descricao: "Atividade médica ambulatorial com recursos para realização de exames" },
  { codigo: "8650-0/01", descricao: "Atividades de enfermagem" },
  { codigo: "8660-7/00", descricao: "Atividades de apoio à gestão de saúde" },
  { codigo: "8711-5/01", descricao: "Clínicas e residências geriátricas" },
  { codigo: "8800-6/00", descricao: "Serviços de assistência social sem alojamento" },
  { codigo: "9001-9/01", descricao: "Produção teatral" },
  { codigo: "9103-1/00", descricao: "Atividades de jardins botânicos, zoológicos e parques nacionais" },
  { codigo: "9420-1/00", descricao: "Atividades de organizações sindicais" },
  { codigo: "9601-7/01", descricao: "Lavanderias" },
  { codigo: "9602-5/01", descricao: "Cabeleireiros" },
  { codigo: "9609-2/99", descricao: "Outras atividades de serviços pessoais" },
]

export function buscarCnaes(query: string, max = 6): CnaeSugerido[] {
  const q = query.toLowerCase().replace(/\D/g, (c) => (/\s/.test(c) ? " " : c))
  const qRaw = query.toLowerCase()
  return CNAES_SUGERIDOS.filter(
    (c) =>
      c.codigo.toLowerCase().includes(qRaw) ||
      c.descricao.toLowerCase().includes(qRaw) ||
      c.codigo.replace(/\D/g, "").includes(q.replace(/\D/g, ""))
  ).slice(0, max)
}
